package tailnet

// The fixtures are the real shapes, pasted from `tailscale status --json`
// and `tailscale serve status --json` on a live tailnet (Tailscale 1.102.4).
// The peer list and most of Self are kept so the tests can prove that key
// material in the answer never reaches a Status field.
//
// Nothing in this file is generated by this package's own encoder. A test
// that round-trips its own output would pass whatever the code does.

// statusRunning is a node that is up, with key expiry set.
const statusRunning = `{
  "Version": "1.102.4-t3caf7d9e7-g084ee3b64",
  "TUN": true,
  "BackendState": "Running",
  "HaveNodeKey": true,
  "AuthURL": "",
  "TailscaleIPs": [
    "100.64.0.1",
    "fd7a:115c:a1e0::1"
  ],
  "Self": {
    "ID": "nAAAAAAAAA1CNTRL",
    "NodeID": 222222222222222,
    "PublicKey": "nodekey:abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
    "HostName": "stompwatch",
    "DNSName": "stompwatch.example.ts.net.",
    "OS": "linux",
    "UserID": 111111111111111,
    "TailscaleIPs": [
      "100.64.0.1",
      "fd7a:115c:a1e0::1"
    ],
    "Relay": "fra",
    "RxBytes": 0,
    "TxBytes": 0,
    "Created": "2026-03-31T10:28:11.615125293Z",
    "Online": true,
    "ExitNode": false,
    "InNetworkMap": true,
    "KeyExpiry": "2026-09-27T10:28:11Z"
  },
  "Health": [],
  "MagicDNSSuffix": "example.ts.net",
  "CurrentTailnet": {
    "Name": "owner@example.com",
    "MagicDNSSuffix": "example.ts.net",
    "MagicDNSEnabled": true
  },
  "CertDomains": null,
  "ExtraRecords": null,
  "Peer": {
    "nodekey:fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210": {
      "ID": "nBBBBBBBBB1CNTRL",
      "PublicKey": "nodekey:fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210",
      "HostName": "laptop",
      "DNSName": "laptop.example.ts.net.",
      "OS": "linux",
      "TailscaleIPs": [
        "100.64.0.2"
      ],
      "Online": false,
      "InNetworkMap": true
    }
  },
  "User": {
    "111111111111111": {
      "ID": 111111111111111,
      "LoginName": "owner@example.com",
      "DisplayName": "Owner"
    }
  },
  "ClientVersion": null
}
`

// statusNoExpiry is the same node with key expiry disabled: Self carries no
// KeyExpiry field at all, which is how tailscaled says "this key does not
// expire".
const statusNoExpiry = `{
  "Version": "1.102.4-t3caf7d9e7-g084ee3b64",
  "BackendState": "Running",
  "HaveNodeKey": true,
  "Self": {
    "ID": "nAAAAAAAAA1CNTRL",
    "PublicKey": "nodekey:abcdef0123456789abcdef0123456789abcdef0123456789abcdef0123456789",
    "HostName": "stompwatch",
    "DNSName": "stompwatch.example.ts.net.",
    "OS": "linux",
    "Online": true
  },
  "MagicDNSSuffix": "example.ts.net",
  "Health": []
}
`

// statusNeedsLogin is a tailscaled that is running but logged out. The
// command exits 1 and still prints the JSON.
const statusNeedsLogin = `{
  "Version": "1.102.4-t3caf7d9e7-g084ee3b64",
  "BackendState": "NeedsLogin",
  "HaveNodeKey": false,
  "AuthURL": "",
  "Self": {
    "ID": "",
    "PublicKey": "nodekey:0000000000000000000000000000000000000000000000000000000000000000",
    "HostName": "stompwatch",
    "DNSName": "",
    "OS": "linux",
    "Online": false
  },
  "MagicDNSSuffix": "",
  "Health": [
    "state=NeedsLogin, wantRunning=false"
  ]
}
`

// serveNone is what an unconfigured node prints. It is the answer from the
// machine these fixtures were taken on.
const serveNone = `{}
`

// serveDashboard is `tailscale serve --bg http://127.0.0.1:8080`.
const serveDashboard = `{
  "TCP": {
    "443": {
      "HTTPS": true
    }
  },
  "Web": {
    "stompwatch.example.ts.net:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:8080"
        }
      }
    }
  }
}
`

// serveOtherPort proxies something that is not the dashboard.
const serveOtherPort = `{
  "TCP": {
    "443": {
      "HTTPS": true
    }
  },
  "Web": {
    "stompwatch.example.ts.net:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:9090"
        }
      }
    }
  }
}
`

// serveFunnel is the dashboard published to the public internet.
const serveFunnel = `{
  "TCP": {
    "443": {
      "HTTPS": true
    }
  },
  "Web": {
    "stompwatch.example.ts.net:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:8080"
        }
      }
    }
  },
  "AllowFunnel": {
    "stompwatch.example.ts.net:443": true
  }
}
`

// serveFunnelElsewhere puts Funnel on a port that carries something else.
// The dashboard is not published, so Funnel must stay false.
const serveFunnelElsewhere = `{
  "TCP": {
    "443": {
      "HTTPS": true
    },
    "8443": {
      "HTTPS": true
    }
  },
  "Web": {
    "stompwatch.example.ts.net:443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:8080"
        }
      }
    },
    "stompwatch.example.ts.net:8443": {
      "Handlers": {
        "/": {
          "Proxy": "http://127.0.0.1:9090"
        }
      }
    }
  },
  "AllowFunnel": {
    "stompwatch.example.ts.net:8443": true
  }
}
`

// serveForeground is `tailscale serve` without --bg: the config lives under
// Foreground, keyed by the session that holds it, and it serves just the
// same while that session runs.
const serveForeground = `{
  "Foreground": {
    "serve-session-4c1f2a": {
      "TCP": {
        "443": {
          "HTTPS": true
        }
      },
      "Web": {
        "stompwatch.example.ts.net:443": {
          "Handlers": {
            "/dashboard": {
              "Proxy": "http://localhost:8080"
            }
          }
        }
      },
      "AllowFunnel": {
        "stompwatch.example.ts.net:443": true
      }
    }
  }
}
`

// servePlainHTTP is a node serving over HTTP on port 80 rather than HTTPS.
const servePlainHTTP = `{
  "TCP": {
    "80": {
      "HTTP": true
    }
  },
  "Web": {
    "stompwatch.example.ts.net:80": {
      "Handlers": {
        "/": {
          "Proxy": "127.0.0.1:8080"
        }
      }
    }
  }
}
`
